# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
pod 'BaiduMapKit'
pod 'AFNetworking', '~> 3.1.0’
pod 'Masonry', '~> 1.0.1'
target '跑了个步' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for 跑了个步

  target '跑了个步Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target '跑了个步UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
